In [6]:
import pandas as pd
em=pd.DataFrame({"emp_id":[1,2,3,4],"name":["A","B","C","D"],"dept_id":[10,20,30,40]})
print(em)
print("------------------------------>")

dept=pd.DataFrame({"dept_id":[10,20,30],"dept_name":["HR","IT","Finance"]})
print(dept)
print("------------------------------>")

pd.merge(em,dept)

   emp_id name  dept_id
0       1    A       10
1       2    B       20
2       3    C       30
3       4    D       40
------------------------------>
   dept_id dept_name
0       10        HR
1       20        IT
2       30   Finance
------------------------------>

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance

In [7]:
pd.merge(em,dept,on="dept_id",how="inner")

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance

In [8]:
pd.merge(em,dept,on="dept_id",how="outer")

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance
3       4    D       40       NaN

In [9]:
pd.merge(em,dept,on="dept_id",how="left")

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance
3       4    D       40       NaN

In [10]:
pd.merge(em,dept,on="dept_id",how="right")

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance

In [12]:
import pandas as pd
em=pd.DataFrame({"emp_id":[1,2,3,4],"name":["A","B","C","D"],"d_id":[10,20,30,40]})
print(em)
print("------------------------------>")

dept=pd.DataFrame({"dept_id":[10,20,30],"dept_name":["HR","IT","Finance"]})
print(dept)
print("------------------------------>")

pd.merge(em,dept,left_on="d_id",right_on="dept_id")

   emp_id name  d_id
0       1    A    10
1       2    B    20
2       3    C    30
3       4    D    40
------------------------------>
   dept_id dept_name
0       10        HR
1       20        IT
2       30   Finance
------------------------------>

   emp_id name  d_id  dept_id dept_name
0       1    A    10       10        HR
1       2    B    20       20        IT
2       3    C    30       30   Finance

In [15]:
import pandas as pd
em=pd.DataFrame({"emp_id":[1,2,3,4],"name":["A","B","C","D"],"d_id":[10,20,30,40]})
print(em)
print("------------------------------>")

dept=pd.DataFrame({"dept_id":[10,40,20],"dept_name":["HR","IT","Finance"]})
print(dept)
print("------------------------------>")

pd.merge(em,dept,left_index=True,right_index=True)

   emp_id name  d_id
0       1    A    10
1       2    B    20
2       3    C    30
3       4    D    40
------------------------------>
   dept_id dept_name
0       10        HR
1       40        IT
2       20   Finance
------------------------------>

   emp_id name  d_id  dept_id dept_name
0       1    A    10       10        HR
1       2    B    20       40        IT
2       3    C    30       20   Finance

In [5]:
import pandas as pd
em=pd.DataFrame({"emp_id":[1,2,3,4],"name":["A","B","C","D"],"dept_id":[10,20,30,40],"updated":[1,2,3,4]})
print(em)
print("------------------------------>")

dept=pd.DataFrame({"dept_id":[10,20,30],"dept_name":["HR","IT","Finance"],"updated":[1,2,3]})
print(dept)
print("------------------------------>")

pd.merge(em,dept,on="dept_id")
pd.merge(em,dept,on="dept_id",suffixes=("_emp","_dept"))

   emp_id name  dept_id  updated
0       1    A       10        1
1       2    B       20        2
2       3    C       30        3
3       4    D       40        4
------------------------------>
   dept_id dept_name  updated
0       10        HR        1
1       20        IT        2
2       30   Finance        3
------------------------------>

   emp_id name  dept_id  updated_emp dept_name  updated_dept
0       1    A       10            1        HR             1
1       2    B       20            2        IT             2
2       3    C       30            3   Finance             3

groupby()

In [22]:
import pandas as pd
df=pd.DataFrame({"dept":["IT","IT","HR","HR","FINANCE","IT","HR"],
                "emp":["A","B","C","D","E","F","C"],
                "salary":[50000,40000,60000,75000,55000,30000,48000],
                "exp":[2,3,1,2,5,4,1]})

print(df)
print("------------------------------>")

df.groupby("dept").sum(numeric_only=True)

      dept emp  salary  exp
0       IT   A   50000    2
1       IT   B   40000    3
2       HR   C   60000    1
3       HR   D   75000    2
4  FINANCE   E   55000    5
5       IT   F   30000    4
6       HR   C   48000    1
------------------------------>

         salary  exp
dept
FINANCE   55000    5
HR       183000    4
IT       120000    9

In [18]:
df.groupby("dept")["salary"].sum(numeric_only=True)

dept
FINANCE     55000
HR         183000
IT         120000
Name: salary, dtype: int64

In [20]:
df.groupby("dept").mean(numeric_only=True)

          salary       exp
dept
FINANCE  55000.0  5.000000
HR       61000.0  1.333333
IT       40000.0  3.000000

In [23]:
print(df.groupby(["dept","exp"]).sum(numeric_only=True))

             salary
dept    exp
FINANCE 5     55000
HR      1    108000
        2     75000
IT      2     50000
        3     40000
        4     30000

In [25]:
print(df.groupby("dept",sort=False).sum(numeric_only=True))

         salary  exp
dept
IT       120000    9
HR       183000    4
FINANCE   55000    5

In [26]:
df.groupby("dept").agg({"salary":["min","max","mean"],"exp":["mean"]})

        salary                       exp
           min    max     mean      mean
dept
FINANCE  55000  55000  55000.0  5.000000
HR       48000  75000  61000.0  1.333333
IT       30000  50000  40000.0  3.000000

In [27]:
df.groupby("dept").groups

{'FINANCE': [4], 'HR': [2, 3, 6], 'IT': [0, 1, 5]}

In [28]:
df.groupby("dept").describe()

        salary                                                             \
         count     mean           std      min      25%      50%      75%
dept
FINANCE    1.0  55000.0           NaN  55000.0  55000.0  55000.0  55000.0
HR         3.0  61000.0  13527.749258  48000.0  54000.0  60000.0  67500.0
IT         3.0  40000.0  10000.000000  30000.0  35000.0  40000.0  45000.0

                   exp
             max count      mean      std  min  25%  50%  75%  max
dept
FINANCE  55000.0   1.0  5.000000      NaN  5.0  5.0  5.0  5.0  5.0
HR       75000.0   3.0  1.333333  0.57735  1.0  1.0  1.0  1.5  2.0
IT       50000.0   3.0  3.000000  1.00000  2.0  2.5  3.0  3.5  4.0

In [30]:
df.groupby("dept").nunique()

         emp  salary  exp
dept
FINANCE    1       1    1
HR         2       3    2
IT         3       3    3

In [31]:
df.groupby("dept")["salary"].apply(lambda x:x.max()-x.min())

dept
FINANCE        0
HR         27000
IT         20000
Name: salary, dtype: int64

In [32]:
df.groupby("dept").nth(0)

      dept emp  salary  exp
0       IT   A   50000    2
2       HR   C   60000    1
4  FINANCE   E   55000    5

In [33]:
df.groupby("dept").nth(-1)

      dept emp  salary  exp
4  FINANCE   E   55000    5
5       IT   F   30000    4
6       HR   C   48000    1

In [36]:
df.groupby("dept").nth([0,-1])

      dept emp  salary  exp
0       IT   A   50000    2
2       HR   C   60000    1
4  FINANCE   E   55000    5
5       IT   F   30000    4
6       HR   C   48000    1

In [41]:
def label_high(g):
    g["high_earner"]=g["salary"]>=g["salary"].mean()
    return g

res=df.groupby("dept").apply(label_high)
res

C:\Users\LJENG\AppData\Local\Temp\ipykernel_10320\4003393626.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  res=df.groupby("dept").apply(label_high)

              dept emp  salary  exp  high_earner
dept
FINANCE 4  FINANCE   E   55000    5         True
HR      2       HR   C   60000    1        False
        3       HR   D   75000    2         True
        6       HR   C   48000    1        False
IT      0       IT   A   50000    2         True
        1       IT   B   40000    3         True
        5       IT   F   30000    4        False