In [1]:
import pandas as pd
l=[18,20,10,12,15]
b=[20,20,10,15,17]
df=pd.DataFrame({"length":l,"breadth":b})
print(df)

   length  breadth
0      18       20
1      20       20
2      10       10
3      12       15
4      15       17

In [11]:
import pandas as pd
l=[18,20,10,12,15]
b=[20,20,10,15,17]
df=pd.DataFrame({"length":l,"breadth":b})
df["area"]=df["length"]*df["breadth"]
#df["area1"]=df["area"]+20
df["price"]=[2000000,4000000,5000000,3000000,1500000]
print(df)
import numpy as np
df["price"]=np.where(df["price"]>=300000,"high",np.where(df["price">=200000,"med","low"]))
df

   length  breadth  area    price
0      18       20   360  2000000
1      20       20   400  4000000
2      10       10   100  5000000
3      12       15   180  3000000
4      15       17   255  1500000

TypeError: '>=' not supported between instances of 'str' and 'int'

In [4]:
df=pd.DataFrame({"rollno":[1,2,3,4,5],"city":["a","b","c","b","a"]})
print(df)
df1=pd.get_dummies(data=df,drop_first=True)
df1

   rollno city
0       1    a
1       2    b
2       3    c
3       4    b
4       5    a

   rollno  city_b  city_c
0       1   False   False
1       2    True   False
2       3   False    True
3       4    True   False
4       5   False   False

In [5]:
df2=pd.get_dummies(data=df)
df2

   rollno  city_a  city_b  city_c
0       1    True   False   False
1       2   False    True   False
2       3   False   False    True
3       4   False    True   False
4       5    True   False   False